// ═══════════════════════════════════════════════
//  DOWNLOAD REPORT
// ═══════════════════════════════════════════════
function downloadReport() {
  const a = State.currentAnalysis;
  if (!a) return;
  const name = State.profile?.full_name || State.user?.user_metadata?.full_name || 'User';
  const date = new Date().toLocaleString();
  const fillers = (a.fillerWords || []).map(f => `${f.word}: ${f.count}`).join(', ') || 'None';
  const pauses = (a.pauses || []).length;
  const recs = (a.recommendations || []).map((r, i) => `${i+1}. [${r.priority?.toUpperCase()}] ${r.title}\n   ${r.description}\n   → ${r.action}`).join('\n\n');
  const transcript = a.transcript || 'No transcript available';
  const report = `
═══════════════════════════════════════════════════════
              VOXIQ AI VOICE ANALYZER REPORT
═══════════════════════════════════════════════════════

Analyst: ${name}
Date: ${date}
Duration: ${Math.floor((a.duration||0)/60)}m ${Math.round((a.duration||0)%60)}s
Words: ${(a.words||[]).length}

───────────────────────────────────────────────────────
OVERALL SCORE: ${a.overallScore || 0}/100
───────────────────────────────────────────────────────

VOICE METRICS
─────────────
• Average WPM: ${a.wpmAverage || 0} (Ideal: 120–160)
• Dominant Emotion: ${a.dominantEmotion || 'N/A'}
• Vocal Variety Score: ${a.vocalVarietyScore || 0}/100
• Total Filler Words: ${(a.fillerWords||[]).reduce((s,f)=>s+f.count,0)}
• Long Pauses (≥2s): ${pauses}

EMOTION BREAKDOWN
─────────────────
${(a.emotions||[]).map(e => `• ${e.emotion}: ${e.percentage}%`).join('\n')}

FILLER WORDS
────────────
${fillers}

───────────────────────────────────────────────────────
AI RECOMMENDATIONS
───────────────────────────────────────────────────────

${recs}

───────────────────────────────────────────────────────
TRANSCRIPT
───────────────────────────────────────────────────────

${transcript}

═══════════════════════════════════════════════════════
Generated by VoxIQ AI Voice Analyzer | voxiq.ai
═══════════════════════════════════════════════════════`;

  const blob = new Blob([report], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `VoxIQ_Report_${new Date().toISOString().split('T')[0]}.txt`;
  link.click();
  URL.revokeObjectURL(url);
  toast('Report downloaded!', 'success');
}
